# ./docker-compose.yml

version: '3'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: clickadu
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "9906:3306"
  web:
    build:
      context: .
    depends_on:
      - db
    volumes:
      - ./:/var/www/
    ports:
      - "8100:80"
    stdin_open: true
    tty: true